### ISSUE TITLE
Determine Hardware License

### ISSUE THREAD

**Issue by Zuph** [whitestarballoon/Iridium-Shield#1]
Looking at CERN-OHL

**Comment by steamfire** [comment]
A commonly known license is more respectful of the end user's time required to understand it, why not just use a CC type?  Several common arduino boards do:

http://arduino.cc/en/uploads/Main/Arduino-Fio-schematic.pdf
http://www.ladyada.net/make/pshield/download.html
http://dangerousprototypes.com/2010/11/17/open-source-arduino-shield-outline-in-geda/
http://dangerousprototypes.com/docs/Bus_Pirate#License

**Comment by Zuph** [comment]
Sounds good.

**Comment by steamfire** [comment]
CC-BY?

**Comment by Zuph** [comment]
I like CC-BY-SA, but that's because I'm a dirty commie.

**Comment by Zuph** [comment]
CC-BY-SA until further notice.  It's easy to go from a more restrictive license to a less restrictive license.  The opposite is more difficult.

**Comment by steamfire** [comment]
sounds good!
