### ISSUE TITLE
Add reverse current protection to external 5V power terminal

### ISSUE THREAD

**Issue by steamfire** [whitestarballoon/Iridium-Shield#10]

**Comment by Zuph** [comment]
Possible Solutions:
1. LDO Diode
   - Pros: Simple
   - Cons: Voltage Drop
2. Shunt Diode
   - Pros: Simple
   - Cons: High current-draw in reverse situation
3. PMOS in Power Path
   - Pros: Low Dropout, No current draw
   - Cons: Difficult to find PMOS with both Low RDS _and_ >4 amp constant current
4. Low Side Switch
   - Pros: Easy
   - Cons: Disrupts ground-return paths

I like option 3.

**Comment by Zuph** [comment]
fixed in 3f40ae46eedc8f3f8e189dc41fd74c22e5bcdc62
