### ISSUE TITLE
Add Inrush current protection

### ISSUE THREAD

**Issue by steamfire** [whitestarballoon/Iridium-Shield#11]
The 9602 needs to have in-rush current limited to 4A.  An NTC Thermistor may be the easiest solution

**Comment by Zuph** [comment]
Steady state resistance of ntc may drop voltage unacceptably. May research
ptc in parallel with current limiting resistor.
On Jan 16, 2012 9:53 AM, "Dan Bowen" <
reply@reply.github.com>
wrote:

**Comment by Zuph** [comment]
Indeed, NTC would result in ~400mA current drain at full satellite load.  At Balloon Expected Average Load (~100mA), NTC results in additional 20mA load.

PTC with trip-current of 3A in parallel with NTC would allow stead-state current drain of ~20mA at full satellite load, and ~2mA Average Load.  Should still adequately block inrush current.

**Comment by steamfire** [comment]
interesting pairup.  The alternative is an inductor, but I'm much more hazy on how to calculate that.

**Comment by Zuph** [comment]
Another possibility is an NTC with a MOSFET, but this would require active control (or another reset chip with delay).

An inductor would be nice.  NTC with PTC seems elegant, if it works.  If it doesn't, PTC could be omitted and we could just live with the current draw.

**Comment by imrcly** [comment]
adjustable 5v 4amp current and voltage regulating

http://octopart.com/ir3842mtr1pbf-international+rectifier-11855068

would make it easier and cheaper as a shield to just use this rather than require an external power board could also put on a trimpot to tune the voltage and could power the ardiuno if connected to the 5v pin

**Comment by Zuph** [comment]
Pain to solder and integrate for this revision.  Maybe version 2.

**Comment by steamfire** [comment]
I don't think it's a good idea. 

The shield can be distributed without any major voltage regulator onboard.  It will be able to operate off of the Arduino 5V voltage regulator alone for most people, if they don't transmit too often.  The supercap will be selected to provide 100% of the transmit power, and will just take a minute or two to recover fully when using the arduino regulator.  If they want to transmit more often, they can buy the add-on regulator, or supply an external 5v supply with more current available.

Also that part requires like 10 extra SMD components.

**Comment by imrcly** [comment]
it also provides the needed protection from inrush current.

**Comment by steamfire** [comment]
keeping costs down on the power regulator circuit will make it more attractive to sell and buy, and on a mass-produced version the more parts you put on the longer it takes to source vendors, assemble, and quality check, so cost for manufacture goes up with part count.  an inductor or NTC are one or two part solutions, and if we find them to be improper, or more expensive than this multipart solution we may need to try this.
