### ISSUE TITLE
Change brownout detector

### ISSUE THREAD

**Issue by steamfire** [whitestarballoon/Iridium-Shield#13]
Currently: TC54 Microchip
     This one only triggers at 4.5v, far too low.
Proposed: Rohm BU4348__G
    Rohm part is available precisely to trigger when below 4.8v and will trigger after 0.9ms of voltage droop.

**Comment by Zuph** [comment]
Recommend another selection, due to part availability
On Jan 16, 2012 3:27 PM, "Dan Bowen" <
reply@reply.github.com>
wrote:

**Comment by Zuph** [comment]
Suggest as Alternative: Rohm BD4848

**Comment by steamfire** [comment]
Looks like a great replacement!  response time is good, 1mS, hysteresis is 0.05v, and hookup requires no extra parts.  Good availibilty and price.
