### ISSUE TITLE
Modify C̶r̶e̶a̶t̶e̶ Footprint for 9602

### ISSUE THREAD

**Issue by Zuph** [whitestarballoon/Iridium-Shield#2]
Modify C̶r̶e̶a̶t̶e̶ footprint from developer manual

**Comment by steamfire** [comment]
Tim already created this

Thanks,
Dan

**Comment by Zuph** [comment]
Tim has already _mostly_ created this.

Needs verification of spacing, and addition of MMCX connectors.  Current
footprint merely has a big hole for MMCX connectors.

On Wed, Jan 11, 2012 at 1:19 PM, Dan Bowen <
reply@reply.github.com

> wrote:
> 
> Tim already created this
> 
> Thanks,
> Dan
> 
> Sent from my iPhone
>

**Comment by steamfire** [comment]
well, then I'd say modify, not create :-P
