### ISSUE TITLE
Power Capacitor

### ISSUE THREAD

**Issue by imrcly** [whitestarballoon/Iridium-Shield#5]
http://octopart.com/255dcn5r4q-illinois+capacitor-8159693   $4.08
Rated for -40c to +60c
5.4v 1.5F  overkill 
rated(A) 0.765      MAX(A) 3.1  
ESR 200mOhm

http://octopart.com/255dcn5r4q-illinois+capacitor-8159858   $5.42
255DCN5R4Q
5.4v  2.5F  overkill 
Rated(A)1.3        MAX(A)5.1 
ESR 130mOhm

**Comment by Zuph** [comment]
Documented in PARTS.md, added 4da6194db2632e813ba595f76006973632a696de
