### ISSUE TITLE
Place sat modem at end edge of the board or on bottom

### ISSUE THREAD

**Issue by steamfire** [whitestarballoon/Iridium-Shield#8]
So that the 9602 antenna connector can be drilled through by hand to allow straight-in coax connector to connect to modem.  May want to use tall header pins as a result.

**Comment by Zuph** [comment]
Do we have a source for MMCX iridium antennas?

**Comment by steamfire** [comment]
not that I know of, I just want to leave the option open for someone to use an easier-to-solder connector if they want to make a cable.

**Comment by Zuph** [comment]
Unfeasible for first run.
